#+title: consult-recoll

[[https://www.lesbonscomptes.com/recoll/][Recoll]] queries in emacs using [[https://github.com/minad/consult][consult]].

This package requires a working recoll index, and ~recollq~ in your
path.

  - =M-x consult-recoll= to perform a query on the index using
    consult.
  - See also the associated customization group for ways to tweak the
    command's behaviour (e.g., how the selected candidate is visited).

~consult-recoll~ builds on the asychronous logic inside =consult.el=, so
you can use consult's handy [[https://github.com/minad/consult#asynchronous-search][two-level filtering]], which allows
searching over the results of a query. For example, if you start
typing

    #goedel's theorem

see a bunch of results, and want to narrow them to those lines
matching, say, "hofstadter", you can type ~#~ (which stops further
recoll queries) followed by the term you're interested in:

   #goedel's theorem#hofstadter

at which point only matches containing "hofstadter" will be offered.
